#lang racket
(display "Задание. Сортировка пузырьком")
(display "\nВведите список в формате (3 2 1): ")
(define lst0 (read))
(define (buble-sort lst)
(define sorted-list lst)
(define temp 0)
(if (> 2 (length lst))
(void)
(begin
(for/list ([i (- (length lst) 1)])
(for/list ([j (-(- (length lst) 1) i)])
(if (> (list-ref sorted-list j) (list-ref sorted-list (+ j 1)))
(begin
(set! temp (list-ref sorted-list (+ j 1)))
(set! sorted-list (list-set sorted-list (+ j 1) (list-ref sorted-list j)))
(set! sorted-list (list-set sorted-list j temp)))
(void))))))
sorted-list)

(buble-sort lst0)

(display "Задание. Сортировка вставками (чтобы не повторяться)")
(define (insert x lst)
  (if (null? lst)
      (list x)
      (let ((y (car lst))
            (ys (cdr lst)))
        (if (<= x y)
            (cons x lst)
            (cons y (insert x ys))))))
(define (insertion-sort lst)
  (if (null? lst)
      '()
      (insert (car lst)
              (insertion-sort (cdr lst)))))
(display "\n")
(insertion-sort lst0)
