#lang racket
(display  "1 Задание. Вычисление площади кольца. " )
(display "\nРадиус кольца (>=5): ")
(define R (read))
(display "Радиус отверстия (>=6): ")
(define r (read))
(if (and (>= R 5) (>= r 6) (> R r))
(and (display "Площадь круга: ") (display ( * (- (* R R) (* r r)) 3.14)))
(display "Ошибка! Радиус отверстия не может быть больше радиуса кольца."))

(display  "\n")
(display  "\n2 Задание. В каком году началась вторая мировая война?" )
(display "\nВведите год: ")
(define y (read))
(if (= y 1939)
(display "Правильно ")
(display "Неправильно. Вторая мировая война началась в 1939 г."))

(display  "\n")
(display  "\n3 Задание. Вывод времени года в зависимости от месяца" )
(display "\nВведите номер месяца (число от 1 до 12): ")
(define mon (read))
(cond ((or (<= mon 2) (= mon 12)) (display "Зима"))
((and (> mon 2)(<= mon 5))  (display "Весна"))
((and (> mon 5)(<= mon 8))  (display "Лето"))
((and (> mon 8)(<= mon 11)) (display "Осень"))
((> mon 12) (display "Ошибка!")))
