#lang racket
(display "1 задание. Введите длину ребра: ")
(define a (read))
(define v(* a a a))
(display "Объем куба: ")
(display v)
(display " куб.см")

(display "\n2 Задание. Введите радиус основания: ")
(define r (read))
(display "Введите высоту цилиндра: ")
(define h (read))
(define vol (* (* 3.14 h) (* r r)))
(display "Объем цилиндра: ")
(display vol)
(display " см.куб")

(display "\n3 Задание. Цена тетради ")
(define ct (read))
(display "Кол-во тетрадей: ")
(define kt (read))
(display "Цена карандаша: ")
(define ck (read))
(display "Кол-во карандашей: ")
(define kk (read))
(define sum (+ (* ct kt ) (* ck kk)))
(display "Стоимость покупки: ")
(display sum)
(display " руб")
